workflows:
  build_flutter:
    name: Build Flutter Project

    environment:
      flutter: stable

    scripts:
      - flutter --version
      - flutter pub get

      # إذا المشروع ناقص، أنشئه
      - flutter create . --org btc --project-name crypto_analysis || true

      - flutter pub get
      - flutter build apk
